# Generated by Django 6.0.7 on 2026-07-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=30)),
                ('fuel_type', models.CharField(max_length=30)),
                ('rental_price', models.FloatField()),
                ('model_year', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
