# Generated by Django 6.0.7 on 2026-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('thriller', 'Thriller')], max_length=50)),
                ('movie_description', models.TextField()),
                ('movie_duration', models.CharField(max_length=50)),
                ('movie_rating', models.FloatField()),
                ('movie_poster', models.ImageField(upload_to='movies/')),
                ('release_date', models.DateField()),
            ],
        ),
    ]
