# Generated by Django 6.0.7 on 2026-07-17 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Villa', 'Villa'), ('PG', 'PG'), ('Room', 'Room'), ('Office', 'Office')], max_length=20)),
                ('address', models.TextField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('furnishing', models.CharField(max_length=100)),
                ('area_sqft', models.PositiveIntegerField()),
                ('available_from', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Unavailable', 'Unavailable')], default='Available', max_length=20)),
                ('property_image', models.ImageField(upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(to='rentalapp.amenity')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.owner')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.state')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.propertycategory')),
            ],
        ),
    ]
