# Generated by Django 6.0.7 on 2026-07-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0004_contactmessage_propertyimage_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='password',
            field=models.CharField(default='123456', max_length=128),
            preserve_default=False,
        ),
    ]
