# Generated by Django 6.0.7 on 2026-07-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('grocery', 'Grocery'), ('furniture', 'Furniture')], max_length=50)),
                ('product_description', models.TextField()),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='products/')),
                ('created_date', models.DateField()),
            ],
        ),
    ]
